apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hangman-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/gooeytuxedo/hangman-elixir.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hangman-elixir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true