apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hangman-app-tls
spec:
  secretName: hangman-app-tls
  usages:
    - server auth
    - client auth
  commonName: hangman.based.consulting
  dnsNames:
    - hangman.based.consulting
  issuerRef:
    name: civo
    kind: ClusterIssuer
